spring:
  application:
    name: backend
  profiles:
    active: dev
  jpa:
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

server:
  port: 8080
  servlet:
    context-path: / 